id = "roxo-theme"
name = "Roxo theme"
version = "1.0.0"
schema_version = 1
authors = ["Rellyson Silva <noreply>"]
description = "Roxo theme for Zed IDE"
repository = "https://github.com/roxo-theme/zed"
